/**
 * Export utilities — CSV, JSON, Markdown report generation.
 * Also handles scan history persistence in localStorage.
 */

import type { ScanResult } from '../types';

const HISTORY_KEY = 'edam_scan_history';
const MAX_HISTORY = 15;

/* ── History ── */

export function saveToHistory(scan: ScanResult): void {
  const history = loadHistory();
  history.unshift(scan);
  if (history.length > MAX_HISTORY) history.length = MAX_HISTORY;
  try {
    localStorage.setItem(HISTORY_KEY, JSON.stringify(history));
  } catch {
    // Storage quota exceeded — trim more aggressively
    history.length = 5;
    localStorage.setItem(HISTORY_KEY, JSON.stringify(history));
  }
}

export function loadHistory(): ScanResult[] {
  try {
    const raw = localStorage.getItem(HISTORY_KEY);
    return raw ? JSON.parse(raw) : [];
  } catch {
    return [];
  }
}

export function deleteFromHistory(scanId: string): void {
  try {
    const history = loadHistory().filter(s => s.id !== scanId);
    localStorage.setItem(HISTORY_KEY, JSON.stringify(history));
  } catch {
    // If we can't update history, fail silently to avoid breaking the UI
  }
}

/* ── CSV Export ── */

export function exportCsv(scan: ScanResult): string {
  const headers = ['ID', 'Type', 'Value', 'Risk Score', 'Severity', 'Risk Reasons', 'First Seen'];
  const rows = scan.assets.map(a => [
    a.id,
    a.type,
    `"${a.value}"`,
    a.riskScore.toString(),
    a.severity,
    `"${a.riskReasons.join('; ')}"`,
    a.firstSeen,
  ]);
  return [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
}

/* ── JSON Export ── */

export function exportJson(scan: ScanResult): string {
  return JSON.stringify(scan, null, 2);
}

/* ── Markdown Report ── */

export function exportMarkdown(scan: ScanResult): string {
  const s = scan.stats;
  let md = `# External Asset Scan Report\n\n`;
  md += `**Domain:** ${scan.domain}\n`;
  md += `**Date:** ${new Date(scan.timestamp).toLocaleString()}\n`;
  md += `**Duration:** ${(scan.durationMs / 1000).toFixed(1)}s\n\n`;

  md += `## Summary\n\n`;
  md += `| Metric | Value |\n|--------|-------|\n`;
  md += `| Total Assets | ${s.totalAssets} |\n`;
  md += `| Domains | ${s.domains} |\n`;
  md += `| Subdomains | ${s.subdomains} |\n`;
  md += `| IP Addresses | ${s.ips} |\n`;
  md += `| Services | ${s.services} |\n`;
  md += `| Avg Risk Score | ${s.avgRisk} |\n`;
  md += `| Max Risk Score | ${s.maxRisk} |\n`;
  md += `| Critical | ${s.critical} |\n`;
  md += `| High | ${s.high} |\n`;
  md += `| Medium | ${s.medium} |\n`;
  md += `| Low | ${s.low} |\n\n`;

  md += `## Assets by Risk\n\n`;
  md += `| Asset | Type | Risk | Severity | Reasons |\n`;
  md += `|-------|------|------|----------|---------|\n`;

  const sorted = [...scan.assets].sort((a, b) => b.riskScore - a.riskScore);
  for (const a of sorted) {
    md += `| ${a.value} | ${a.type} | ${a.riskScore} | ${a.severity} | ${a.riskReasons.join('; ') || '—'} |\n`;
  }

  if (scan.errors.length > 0) {
    md += `\n## Errors\n\n`;
    for (const e of scan.errors) {
      md += `- ${e}\n`;
    }
  }

  md += `\n---\n*Generated by EDAM — External Digital Asset Mapper*\n`;
  return md;
}

/* ── Download helper ── */

export function downloadFile(content: string, filename: string, mime: string): void {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
